[theme]
primaryColor = "#2E86C1"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1B2631"
textColor = "#EAECEF"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 20
